const bold = document.querySelector("b");
console.log(bold);
bold.parentElement.parentElement.parentElement.parentElement.style.background = "beige";
bold.style.color = "red";
bold.parentElement.parentElement.parentElement.style.color = "white";
bold.parentElement.parentElement.parentElement.style.backgroundColor = "darkblue";
bold.parentElement.parentElement.querySelector("a").style.color = "pink";
bold.parentElement.parentElement.parentElement.parentElement.querySelector("ul").style.color = "orange";
bold.parentElement.parentElement.parentElement.parentElement.querySelector("ul").querySelectorAll("a")[0].style.color = "green";
bold.parentElement.parentElement.parentElement.parentElement.querySelector("ul").querySelectorAll("a")[1].style.color = "green";
bold.parentElement.parentElement.parentElement.parentElement.querySelector("ul").querySelectorAll("a")[2].style.color = "green";
bold.parentElement.parentElement.parentElement.parentElement.querySelector("ul").querySelectorAll("a")[3].style.color = "green";
bold.parentElement.parentElement.parentElement.parentElement.querySelector("ul").querySelectorAll("a")[4].style.color = "green";
bold.parentElement.parentElement.parentElement.parentElement.querySelector("h1").style.textTransform = "uppercase";